spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_booking_system_db
    username: root
    password: root026
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: Hotel-Booking-System

logging:
  level:
    hotel.booking.system.backend: debug

server:
  port: 3030
