spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_booking_system_db
    username: root
    password: root026
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: Hotel-Booking-System
  main:
    banner-mode: off

logging:
  level:
    hotel.booking.system.backend: debug
    root: info
  file:
    name: logs/hotel-booking-system-admin-log.log

server:
  port: 3030
